package skill

import (
	"os"
	"path/filepath"
	"testing"
)

// TestCopyDir_SkipsPythonBytecode pins the publish-snapshot fix: copyDir must
// drop generated Python bytecode (__pycache__/ and *.pyc) so a `qvr publish`
// (or eject) never carries machine-specific compiled artifacts of a skill's
// eval.py into the published fork, while still copying the real source.
func TestCopyDir_SkipsPythonBytecode(t *testing.T) {
	src := t.TempDir()
	dst := filepath.Join(t.TempDir(), "out")

	// A realistic eval/ layout: real source + a generated bytecode cache.
	mustWrite(t, filepath.Join(src, "eval", "eval.py"), "print('grade')\n")
	mustWrite(t, filepath.Join(src, "eval", "__pycache__", "eval.cpython-313.pyc"), "\x00bytecode")
	mustWrite(t, filepath.Join(src, "eval", "scenarios.jsonl"), "{}\n")
	mustWrite(t, filepath.Join(src, "stray.pyc"), "\x00bytecode") // a .pyc outside __pycache__ too

	if err := copyDir(src, dst); err != nil {
		t.Fatalf("copyDir: %v", err)
	}

	// Source survives.
	for _, keep := range []string{"eval/eval.py", "eval/scenarios.jsonl"} {
		if _, err := os.Stat(filepath.Join(dst, keep)); err != nil {
			t.Errorf("expected %s copied: %v", keep, err)
		}
	}
	// Bytecode is dropped — both the whole __pycache__ dir and a loose .pyc.
	for _, gone := range []string{"eval/__pycache__", "eval/__pycache__/eval.cpython-313.pyc", "stray.pyc"} {
		if _, err := os.Stat(filepath.Join(dst, gone)); !os.IsNotExist(err) {
			t.Errorf("expected %s skipped, but it exists (err=%v)", gone, err)
		}
	}
}

func mustWrite(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
