-- 0007: nullable session-level outcome on the unified session read model.
-- The worst-of-spans rollup of each session's TOOL/SKILL qvr.outcome
-- attribute (success/failure/blocked), derived at derive time. NULL means no
-- span carried an outcome — consumers render "unknown", never a fabricated
-- success. Regenerated by `qvr audit rederive` after the v8 deriver bump.
ALTER TABLE session_meta ADD COLUMN outcome TEXT;
